### ISSUE TITLE
Small UUID error?

### ISSUE THREAD

**Issue by DutchUser** [netherfoam/MaxBans#31]
Hello, I think that i found an small bug
if you do only /uuid and not /uuid vocalwolf (or /uuid <player)
that give the console an big error and stand ingame
Maybay its normal but maybay not xD
MaxBans Version: : MaxBans 2.4 (Beta) for 1.8.1
DataBase: SQLIte (FlatFile)
Ingame error,
'Something went wrong when executing the command'
'An internal error occurred while attempting to perform this command'
Console error,
[25-03 10:59:07 ] [Server] WARN java.lang.ArrayIndexOutOfBoundsException: 0
[25-03 10:59:07 ] [Server] WARN at org.maxgamer.maxbans.commands.UUID.run(UUID.java:22)
[25-03 10:59:07 ] [Server] WARN at org.maxgamer.maxbans.commands.CmdSkeleton.onCommand(CmdSkeleton.java:119)
[25-03 10:59:07 ] [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[25-03 10:59:07 ] [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[25-03 10:59:07 ] [Server] WARN at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
[25-03 10:59:07 ] [Server] WARN at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133)
[25-03 10:59:07 ] [Server] WARN at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968)
[25-03 10:59:07 ] [Server] WARN at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[25-03 10:59:07 ] [Server] WARN at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[25-03 10:59:07 ] [Server] WARN at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[25-03 10:59:07 ] [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[25-03 10:59:07 ] [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[25-03 10:59:07 ] [Server] WARN at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
[25-03 10:59:07 ] [Server] WARN at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710)
[25-03 10:59:07 ] [Server] WARN at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
[25-03 10:59:07 ] [Server] WARN at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
[25-03 10:59:07 ] [Server] WARN at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
[25-03 10:59:07 ] [Server] WARN at java.lang.Thread.run(Thread.java:745)
[25-03 10:59:07 ] [Server] ERROR null
[25-03 10:59:07 ] [Server] [Informatie] org.bukkit.command.CommandException: Unhandled exception executing command 'uuid' in plugin MaxBans v2.0
[25-03 10:59:07 ] [Server] [Informatie] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot1.8.3.jar:git-Spigot-beb883d-234e607]
[25-03 10:59:07 ] [Server] [Informatie] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot1.8.3.jar:git-Spigot-beb883d-234e607]
[25-03 10:59:07 ] [Server] [Informatie] at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot1.8.3.jar:git-Spigot-beb883d-234e607]
[25-03 10:59:07 ] [Server] [Informatie] at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133) [spigot1.8.3.jar:git-Spigot-beb883d-234e607]
[25-03 10:59:07 ] [Server] [Informatie] at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) [spigot1.8.3.jar:git-Spigot-beb883d-234e607]
[25-03 10:59:07 ] [Server] [Informatie] at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot1.8.3.jar:git-Spigot-beb883d-234e607]
[25-03 10:59:07 ] [Server] [Informatie] at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot1.8.3.jar:git-Spigot-beb883d-234e607]
[25-03 10:59:07 ] [Server] [Informatie] at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1.8.3.jar:git-Spigot-beb883d-234e607]
[25-03 10:59:37 ] [Server] Skipped 12 lines due to rate limit (30/s)
[25-03 10:59:37 ] [Server] [Informatie] Admins: [HIDDEN]VocalWolf

**Comment by iversenMC** [comment]
Hmh, I just tested it in-game (offline & premium, 1.8) and there should be no problems.

I did experience this when doing /dupeip to a player that hasn't been online after you updated MaxBans, it gave something like that error.

I think it might be global for MaxBans - JOE should've fixed it already, will come with an update soon.
I recommend switching back to the 1.7.4 version for now if commands gives errors.

Will come out with a new update soon, hopefully without any errors :)
The best you can do, is probably restarting and see if it allows you to /uuid now. I am pretty sure you tried to /uuid a player that hadn't been online after you updated MaxBans.

**Comment by DutchUser** [comment]
Oke, Thx :)
