### ISSUE TITLE
Trying to /dupeip

### ISSUE THREAD

**Issue by EndlessSurvival** [netherfoam/MaxBans#36]
Hey guys when I try to run /dupeip I get the following errors

01.04 06:00:29 [Server] WARN at java.lang.Thread.run(Thread.java:745)
01.04 06:00:29 [Server] WARN at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
01.04 06:00:29 [Server] WARN at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
01.04 06:00:29 [Server] WARN at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
01.04 06:00:29 [Server] WARN at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710)
01.04 06:00:29 [Server] WARN at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
01.04 06:00:29 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:262)
01.04 06:00:29 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
01.04 06:00:29 [Server] WARN at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
01.04 06:00:29 [Server] WARN at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
01.04 06:00:29 [Server] WARN at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
01.04 06:00:29 [Server] WARN at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968)
01.04 06:00:29 [Server] WARN at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133)
01.04 06:00:29 [Server] WARN at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
01.04 06:00:29 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
01.04 06:00:29 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
01.04 06:00:29 [Server] WARN at org.maxgamer.maxbans.commands.CmdSkeleton.onCommand(CmdSkeleton.java:119)
01.04 06:00:29 [Server] WARN at org.maxgamer.maxbans.commands.DupeIPCommand.run(DupeIPCommand.java:51)
01.04 06:00:29 [Server] WARN java.lang.NullPointerException

Love the plugin, really good job.

Thanks in advance,
Mark

**Comment by iversenMC** [comment]
Try the lastest version - should work. Otherwise, are you 1.8?
