### ISSUE TITLE
Default reason for mutes

### ISSUE THREAD

**Issue by Rmarmorstein** [netherfoam/MaxBans#41]
Mutes seem to have issues where it does not have a default reason. See the stacktrace provided.

```
[22:30:03 WARN]: java.sql.SQLException: Field 'reason' doesn't have a default value
[22:30:03 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
[22:30:03 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[22:30:03 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[22:30:03 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[22:30:03 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[22:30:03 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[22:30:03 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[22:30:03 WARN]:        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
[22:30:03 WARN]:        at org.maxgamer.maxbans.database.MySQLCore.queue(MySQLCore.java:71)
[22:30:03 WARN]:        at org.maxgamer.maxbans.database.Database.execute(Database.java:62)
[22:30:03 WARN]:        at org.maxgamer.maxbans.MaxBans$2.execute(MaxBans.java:189)
[22:30:03 WARN]:        at org.maxgamer.maxbans.banmanager.BanManager.mute(BanManager.java:921)
[22:30:03 WARN]:        at org.maxgamer.maxbans.banmanager.SyncBanManager.mute(SyncBanManager.java:135)
[22:30:03 WARN]:        at org.maxgamer.maxbans.commands.MuteCommand.run(MuteCommand.java:38)
[22:30:03 WARN]:        at org.maxgamer.maxbans.commands.CmdSkeleton.onCommand(CmdSkeleton.java:119)
[22:30:03 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[22:30:03 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[22:30:03 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642)
[22:30:03 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135)
[22:30:03 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970)
[22:30:03 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[22:30:03 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[22:30:03 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[22:30:03 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[22:30:03 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[22:30:03 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19)
[22:30:03 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718)
[22:30:03 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367)
[22:30:03 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
[22:30:03 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
[22:30:03 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by Rmarmorstein** [comment]
This does duplicate #40 and #39 however, I give a bit more of an explanation.
