### ISSUE TITLE
/dupeip Issue

### ISSUE THREAD

**Issue by itzhalo** [netherfoam/MaxBans#51]
Hello! I really have enjoyed maxbans but the only issue I have been coming across is /dupeip! I am running on 1.8.9 with the latest version. I have everything configured correctly with even a mysql database. The problem is that whenever I try to /dupeip someone it says and internal error has occurred and shows this in the console: 

06.02 01:06:44 [Server] INFO at org.maxgamer.maxbans.commands.CmdSkeleton.onCommand(CmdSkeleton.java:119) ~[?:?]
06.02 01:06:44 [Server] INFO at org.maxgamer.maxbans.commands.DupeIPCommand.run(DupeIPCommand.java:53) ~[?:?]
06.02 01:06:44 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/HoverEvent
06.02 01:06:44 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_11]

If you guys need me to post any more info on this error I will be happy to do so!

**Comment by ostorebror** [comment]
I got this error as well. I have some more console:
11.02 13:43:47 [Server] INFO ostorebror issued server command: /dupeip ostorebror
11.02 13:43:47 [Server] ERROR null
11.02 13:43:47 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'dupeip' in plugin MaxBans v2.0
11.02 13:43:47 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-BT46_1.8.8_02.06.jar:git-Bukkit-3f3c65f]
11.02 13:43:47 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit-BT46_1.8.8_02.06.jar:git-Bukkit-3f3c65f]
11.02 13:43:47 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:620) ~[craftbukkit-BT46_1.8.8_02.06.jar:git-Bukkit-3f3c65f]
11.02 13:43:47 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1106) [craftbukkit-BT46_1.8.8_02.06.jar:git-Bukkit-3f3c65f]
11.02 13:43:47 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:966) [craftbukkit-BT46_1.8.8_02.06.jar:git-Bukkit-3f3c65f]
11.02 13:43:47 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:37) [craftbukkit-BT46_1.8.8_02.06.jar:git-Bukkit-3f3c65f]
11.02 13:43:47 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:9) [craftbukkit-BT46_1.8.8_02.06.jar:git-Bukkit-3f3c65f]
11.02 13:43:47 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-BT46_1.8.8_02.06.jar:git-Bukkit-3f3c65f]
11.02 13:43:47 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
11.02 13:43:47 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
11.02 13:43:47 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit-BT46_1.8.8_02.06.jar:git-Bukkit-3f3c65f]
11.02 13:43:47 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:673) [craftbukkit-BT46_1.8.8_02.06.jar:git-Bukkit-3f3c65f]
11.02 13:43:47 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit-BT46_1.8.8_02.06.jar:git-Bukkit-3f3c65f]
11.02 13:43:47 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629) [craftbukkit-BT46_1.8.8_02.06.jar:git-Bukkit-3f3c65f]
11.02 13:43:47 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537) [craftbukkit-BT46_1.8.8_02.06.jar:git-Bukkit-3f3c65f]
11.02 13:43:47 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
11.02 13:43:47 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/HoverEvent
11.02 13:43:47 [Server] INFO at org.maxgamer.maxbans.commands.DupeIPCommand.run(DupeIPCommand.java:53) ~[?:?]
11.02 13:43:47 [Server] INFO at org.maxgamer.maxbans.commands.CmdSkeleton.onCommand(CmdSkeleton.java:119) ~[?:?]
11.02 13:43:47 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-BT46_1.8.8_02.06.jar:git-Bukkit-3f3c65f]
11.02 13:43:47 [Server] INFO ... 15 more
11.02 13:43:47 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.HoverEvent
11.02 13:43:47 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_72]
11.02 13:43:47 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-BT46_1.8.8_02.06.jar:git-Bukkit-3f3c65f]
11.02 13:43:47 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-BT46_1.8.8_02.06.jar:git-Bukkit-3f3c65f]
11.02 13:43:47 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_72]
11.02 13:43:47 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_72]
11.02 13:43:47 [Server] INFO at org.maxgamer.maxbans.commands.DupeIPCommand.run(DupeIPCommand.java:53) ~[?:?]
11.02 13:43:47 [Server] INFO at org.maxgamer.maxbans.commands.CmdSkeleton.onCommand(CmdSkeleton.java:119) ~[?:?]
11.02 13:43:47 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-BT46_1.8.8_02.06.jar:git-Bukkit-3f3c65f]
11.02 13:43:47 [Server] INFO ... 15 more

**Comment by itzhalo** [comment]
It's been almost 14 days and no help

**Comment by netherfoam** [comment]
I've got no idea why it's breaking. I'm not supporting this plugin anymore,
it's been a few years.

**Comment by netherfoam** [comment]
Possibly try spigot

**Comment by itzhalo** [comment]
You shouldn't stop supporting this plugin its great, all it needs is a simple fix :/
