### ISSUE TITLE
Maxbans Mysql Bug when a player is joining

### ISSUE THREAD

**Issue by DarkNOD** [netherfoam/MaxBans#61]
[21:24:27] [User Authenticator #356/INFO]: UUID of player DarkNOD is eaeb78cb-f66c-407c-88a0-76bb503e0dfd
[21:24:27] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'name' in 'field list'
[21:24:27] [Server thread/WARN]: 	at sun.reflect.GeneratedConstructorAccessor193.newInstance(Unknown Source)
[21:24:27] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[21:24:27] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[21:24:27] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[21:24:27] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:382)
[21:24:27] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[21:24:27] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[21:24:27] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[21:24:27] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[21:24:27] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[21:24:27] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[21:24:27] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[21:24:27] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
[21:24:27] [Server thread/WARN]: 	at org.maxgamer.maxbans.database.MySQLCore.queue(MySQLCore.java:66)
[21:24:27] [Server thread/WARN]: 	at org.maxgamer.maxbans.database.Database.execute(Database.java:40)
[21:24:27] [Server thread/WARN]: 	at org.maxgamer.maxbans.MaxBans$2.execute(MaxBans.java:147)
[21:24:27] [Server thread/WARN]: 	at org.maxgamer.maxbans.banmanager.BanManager.logActual(BanManager.java:842)
[21:24:27] [Server thread/WARN]: 	at org.maxgamer.maxbans.listeners.JoinListener.onJoinHandler(JoinListener.java:151)
[21:24:27] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor370.invoke(Unknown Source)
[21:24:27] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:24:27] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:24:27] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[21:24:27] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[21:24:27] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[21:24:27] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[21:24:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.attemptLogin(PlayerList.java:456)
[21:24:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:118)
[21:24:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54)
[21:24:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231)
[21:24:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148)
[21:24:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814)
[21:24:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[21:24:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[21:24:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[21:24:27] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by DarkNOD** [comment]
Hello,
Can you help me please?
Thanks you guys
