### ISSUE TITLE
Error in bungee-cord console.

### ISSUE THREAD

**Issue by Bradisswag** [netherfoam/MaxBans#65]
I would be grateful if i had some help on this, Thanks
10:40:01 [WARNING] Error enabling plugin MaxBans
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$100(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:34)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:304)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:263)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 18 more

**Comment by TheMajesticMagician** [comment]
I've got this error as well!

**Comment by dirkredeye** [comment]
This isn't a bungeecord plugin. It seems like you're loading it as one, somehow?

**Comment by netherfoam** [comment]
This isn't a bungeecord plugin. It seems like you're loading it as one, somehow?

**Comment by Bradisswag** [comment]
MaxBans is a spigot AND bungeecord plugin,
The bungeecord plugin acts as a bridge and bans from the whole network instead of just one sub server.

Cannot remember exactly how i fixed this, but go download maxbans-plus, it works like a charm: https://www.spigotmc.org/resources/maxbans-plus.41392/

**Comment by Bradisswag** [comment]
My bad, just remembered that I actually took this plugin and turned it into my own bungeecord plugin. Sorry!

**Comment by netherfoam** [comment]
Heh, was going to say. I'm the original author of the plugin
