### ISSUE TITLE
DupeIP Causes error when being executed in-game

### ISSUE THREAD

**Issue by Livaco** [netherfoam/MaxBans#72]
I can use DupeIP in the console just fine, but when i execute it in-game it brings up this error:
`[18:30:35 INFO]: LivacoYT issued server command: /dupeip 0FJ
[18:30:35 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dupeip' in plugin MaxBans v2.7
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:631) ~[craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1333) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1193) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:696) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/HoverEvent
        at org.maxgamer.maxbans.commands.DupeIPCommand.run(DupeIPCommand.java:58) ~[?:?]
        at org.maxgamer.maxbans.commands.CmdSkeleton.onCommand(CmdSkeleton.java:83) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        ... 15 more`

Im using Bukkit 1.12.2.
Thanks!

**Comment by Livaco** [comment]
@netherfoam @FabioZumbi12 @joehot200 @Iversen

**Comment by FabioZumbi12** [comment]
`net/md_5/bungee/api/chat/HoverEvent`, you need to use Spigot, not craftbukkit.

**Comment by Livaco** [comment]
Thanks that worked!
