### ISSUE TITLE
DupeIp problem

### ISSUE THREAD

**Issue by adsasdadaxgv** [netherfoam/MaxBans#86]
Hi, my minecraft user is PolWall but
when I try to do the /dupeip command I get this:

something went wrong when executing the command:
/dupeip PolWall
Exception: JsonParseException: Invalid color name: reset
The remainder of the exception is in the console,
Please report this tonetherfoam:
http://dev.bukkit.otg/server-mods/maxbans and include the
error in the console in your post

the error console is:
com.google.gson.JsonParseException: Invalid color name: reset
[15:49:47 WARN]:        at net.minecraft.SystemUtils.a(SystemUtils.java:879)
[15:49:47 WARN]:        at net.minecraft.network.chat.IChatBaseComponent$ChatSerializer.b(IChatBaseComponent.java:291)
[15:49:47 WARN]:        at net.minecraft.network.chat.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:310)
[15:49:47 WARN]:        at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(ClientboundSystemChatPacket.java:12)
[15:49:47 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3271)
[15:49:47 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3259)
[15:49:47 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3239)
[15:49:47 WARN]:        at MaxBans (2).jar//org.maxgamer.maxbans.commands.DupeIPCommand.run(DupeIPCommand.java:61)
[15:49:47 WARN]:        at MaxBans (2).jar//org.maxgamer.maxbans.commands.CmdSkeleton.onCommand(CmdSkeleton.java:83)
[15:49:47 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:49:47 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[15:49:47 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:987)
[15:49:47 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[15:49:47 WARN]:        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[15:49:47 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.a(ExecuteCommand.java:32)
[15:49:47 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[15:49:47 WARN]:        at net.minecraft.commands.execution.UnboundEntryAction.a(UnboundEntryAction.java:8)
[15:49:47 WARN]:        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5)
[15:49:47 WARN]:        at net.minecraft.commands.execution.ExecutionContext.a(ExecutionContext.java:101)
[15:49:47 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:434)
[15:49:47 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:336)
[15:49:47 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:323)
[15:49:47 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2216)
[15:49:47 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$16(PlayerConnection.java:2176)
[15:49:47 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[15:49:47 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[15:49:47 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:49:47 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[15:49:47 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[15:49:47 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1455)
[15:49:47 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[15:49:47 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[15:49:47 WARN]:        at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1432)
[15:49:47 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1355)
[15:49:47 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[15:49:47 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1506)
[15:49:47 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1216)
[15:49:47 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[15:49:47 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by Xreoy** [comment]
+1
